<template>
  <main class="home">
    <div class="horizontal-line"></div>
    <div class="container-mid">
      <div class="about-me">
        <h1>{{ introHeading }}</h1>
        <p ref="thisIsMe">
          <IconGentleman class="image-for-text" /><span v-html="introText"></span>
        </p>
      </div>
    </div>
    <div class="container-mid projects">
      <se-projects
        v-for="project in translations.projects"
        :key="project.id"
        :translations="project"
      />
    </div>
  </main>
</template>

<script setup>
import { onBeforeUnmount, onMounted, onUpdated, ref, watch } from 'vue'

import SeProjects from '../components/Projects.vue'
import english from '../assets/translations/english.js'
import IconGentleman from '../components/icons/IconGentleman.vue'

// Translations
const translations = english.data[0].homeView
const { introHeading, introText } = english.data[0].homeView

// Data
const thisIsMe = ref(null)

// Functions
const typeText = () => {
  let delay = 0 // Adjust delay between transitions
  thisIsMe.value.childNodes[1].childNodes.forEach((element) => {
    if (element.nodeName === 'STRONG') {
      setTimeout(() => {
        element.classList.add('type')
      }, delay)
      delay += 600 // Handle delay
    }
  })
}

// Lifecycle Hooks
onMounted(() => {
  typeText()
})
</script>

<style scoped lang="scss">
.home {
  border-left: 2px solid #000;
  margin-left: 29px;
  position: relative;
  h1 {
    padding-top: 80px;
    margin-bottom: 20px;
    &:before {
      content: '';
      height: 2px;
      width: 20px;
      position: absolute;
      display: block;
    }
  }
  .about-me {
    padding-bottom: 22px;
    padding-left: 15px;
    padding-right: 15px;
  }
}
.container-mid p span :deep(strong) {
  padding: 0;
  letter-spacing: -0.5em;
  opacity: 0;
}
.container-mid p span :deep(strong.type) {
  padding: 0 4px;
  -webkit-animation: focus-in-expand 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: focus-in-expand 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.image-for-text {
  width: 200px;
  float: right;
}

.horizontal-line {
  position: relative;
  height: 2px;
  position: absolute;
  top: 0;
  left: 0;
  width: 0;
  background-color: #000;
  animation: left-to-right 1s ease-out forwards;
  animation-delay: 3.2s;
}

.projects {
  margin-top: 60px;
  display: flex;
  gap: 25px;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-12-1 22:57:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand
 * ----------------------------------------
 */
@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    letter-spacing: 0;
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}

@keyframes left-to-right {
  0% {
    opacity: 0;
    width: 0;
  }
  100% {
    opacity: 1;
    width: 100%;
  }
}

@media (min-width: 1176px) {
  .home {
    margin-left: 49px;
    padding: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    .container-mid {
      margin-left: -49px;
    }
    .about-me {
      padding-bottom: 22px;
      padding-left: 15px;
      padding-right: 15px;
    }
  }
}
</style>
